### ISSUE TITLE
[⚙] 3rd Party API Error Flow Processing

### ISSUE THREAD

**Issue by enaenen** [42-MyMisters/transcendence#12]
- 서드파티에서 에러가 났을때 어떻게 할지 회의
- 42Intra 에 요청을 보냈을때 Intra 측에서 잘못된 Response가 오거나 에러 코드가 왔을경우 어떻게 처리할지

**Comment by jpham005** [comment]
아마 axios 사용하면 400번대부턴 기본적으로 throw 해줄겁니다.
적당히 로그인 실패로 처리해도 되고... 다른 페이지 만들어주면 더 좋겠죠.

+ 계정 연동 기능 만들면 intra 터져도 가능! 와!
