### ISSUE TITLE
[BE] yaml 의 config 에서 가져오는 정보 get Any 처리

### ISSUE THREAD

**Issue by codeyoma** [42-MyMisters/transcendence#28]
[https://github.com/42-MyMisters/transcendence/pull/14|https://github.com/42-MyMisters/transcendence/pull/14|smart-link]

 

{noformat}@Redirect('https://api.intra.42.fr/oauth/authorize?client_id=' + config.get<any>('intra').client_id + '&redirect_uri=' + config.get<any>('intra').redirect_uri + '&response_type=code', 301){
}
{noformat}

{noformat}config.get<any>{noformat}

* [x] any 타입 변경할 다른 타입 논의 및 찾아보기

**Comment by codeyoma** [comment]
[ From. Jira - Seungduk Seo ] : 
자함님이 적어주신 express response object 를 한번 살펴보도록 하겠습니다

**Comment by lscitl** [comment]
처리 완료된거라 닫겠습니다.
