### ISSUE TITLE
[BE] User module 설정

### ISSUE THREAD

**Issue by codeyoma** [42-MyMisters/transcendence#72]
### User controller에 대한 Swagger API가 보이지 않은 현상!

1. User module을 login module처럼 App module에 포함
2. User module을 login module처럼 설정 세분화 필요 (제가 시도해보았는데 에러가 뜨길래!! 제작자에게 맡기기 ><)

**Comment by lscitl** [comment]
이건 우주님이 처리 하셔서 닫겠습니다 ㅋㅋ
